theme: jekyll-theme-cayman
title: "Prithwish's website"
description: |
  <a href="https://www.linkedin.com/in/prithwish-maiti/">LinkedIn</a> | <a href="https://github.com/PrithwiShM">GitHub</a> | <a href="mailto:prithwish.maiti99@gmail.com">Email Me</a>

# Add this line to include your custom CSS
sass:
  style: compressed

# If using an external custom stylesheet:
assets:
  css:
    - /assets/css/custom.css
