theme: jekyll-theme-cayman
title: Prithwish Maiti
description: Quantitative Finance | Statistical Data Analysis | Global Macroeconomics
# Add this line to include your custom CSS
sass:
  style: compressed

# If using an external custom stylesheet:
assets:
  css:
    - /assets/css/custom.css
